# 数据库配置 (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5433/jiziwai
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
mybatis.mapper-locations=classpath:mappers/*xml
#指定Mybatis的实体目录
mybatis.type-aliases-package=springbootjni.entity
# MyBatis 配置
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# 应用服务 WEB 访问端口
server.port=8080
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Sa-Token 配置
sa-token.token-name=Authorization
sa-token.timeout=2592000
sa-token.activity-timeout=-1
sa-token.is-concurrent=true
sa-token.is-share=true
sa-token.token-style=uuid
sa-token.is-log=false
sa-token.is-read-cookie=false
sa-token.is-read-head=true
sa-token.jwt-secret-key=abccefghijklmnopqas1uvwxyz

