/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class springbootjni_jni_JNIBridge */

#ifndef _Included_springbootjni_jni_JNIBridge
#define _Included_springbootjni_jni_JNIBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     springbootjni_jni_JNIBridge
 * Method:    startListening
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_springbootjni_jni_JNIBridge_startListening
  (JNIEnv *, jobject);

/*
 * Class:     springbootjni_jni_JNIBridge
 * Method:    stopListening
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_springbootjni_jni_JNIBridge_stopListening
  (JNIEnv *, jobject);

/*
 * Class:     springbootjni_jni_JNIBridge
 * Method:    captureImages
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_springbootjni_jni_JNIBridge_captureImages
  (JNIEnv *, jobject, jint);

/*
 * Class:     springbootjni_jni_JNIBridge
 * Method:    reprocessImage
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_springbootjni_jni_JNIBridge_reprocessImage
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     springbootjni_jni_JNIBridge
 * Method:    processImageWithParams
 * Signature: ([BFFIZZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_springbootjni_jni_JNIBridge_processImageWithParams
  (JNIEnv *, jobject, jbyteArray, jfloat, jfloat, jint, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
