/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class springbootjni_jni_SpectraBridgeNative */

#ifndef _Included_springbootjni_jni_SpectraBridgeNative
#define _Included_springbootjni_jni_SpectraBridgeNative
#ifdef __cplusplus
extern "C" {
#endif
#undef springbootjni_jni_SpectraBridgeNative_FULL_CONFIG_SIZE
#define springbootjni_jni_SpectraBridgeNative_FULL_CONFIG_SIZE 512L
/*
 * Class:     springbootjni_jni_SpectraBridgeNative
 * Method:    nativeCreate
 * Signature: (Lspringbootjni/jni/BridgeListener;)J
 */
JNIEXPORT jlong JNICALL Java_springbootjni_jni_SpectraBridgeNative_nativeCreate
  (JNIEnv *, jclass, jobject);

/*
 * Class:     springbootjni_jni_SpectraBridgeNative
 * Method:    nativeDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_springbootjni_jni_SpectraBridgeNative_nativeDestroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     springbootjni_jni_SpectraBridgeNative
 * Method:    nativeConnect
 * Signature: (JLjava/lang/String;IIZ)V
 */
JNIEXPORT void JNICALL Java_springbootjni_jni_SpectraBridgeNative_nativeConnect
  (JNIEnv *, jclass, jlong, jstring, jint, jint, jboolean);

/*
 * Class:     springbootjni_jni_SpectraBridgeNative
 * Method:    nativeDisconnect
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_springbootjni_jni_SpectraBridgeNative_nativeDisconnect
  (JNIEnv *, jclass, jlong);

/*
 * Class:     springbootjni_jni_SpectraBridgeNative
 * Method:    nativeSendReset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_springbootjni_jni_SpectraBridgeNative_nativeSendReset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     springbootjni_jni_SpectraBridgeNative
 * Method:    nativeSendTriggerOnce
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_springbootjni_jni_SpectraBridgeNative_nativeSendTriggerOnce
  (JNIEnv *, jclass, jlong);

/*
 * Class:     springbootjni_jni_SpectraBridgeNative
 * Method:    nativeSendQueryStatus
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_springbootjni_jni_SpectraBridgeNative_nativeSendQueryStatus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     springbootjni_jni_SpectraBridgeNative
 * Method:    nativeSendFullConfig
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_springbootjni_jni_SpectraBridgeNative_nativeSendFullConfig
  (JNIEnv *, jclass, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
